---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flip-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flip
  template:
    metadata:
      labels:
        app: flip
    spec:
      containers:
      - name: tetris
        image: ramakrishna737/pflicart:v1
        ports:
        - containerPort: 3000
  
