---
apiVersion: v1
kind: Service
metadata:
  name: flipcart-clone
spec:
  selector:
    app: flip
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 80
  type: LoadBalancer
