---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  selector:
    app: tflip
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 8081
  type: LoadBalancer
